spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=file:///C:/Users/Vudin/OneDrive/Documents/Rikkei/MD04/Session07/medical-config-repo
spring.cloud.config.server.git.default-label=main
